### PR TITLE
Update to Manifest version 3 Fixes #13 

### LINKED ISSUE #13: Web Extension manifest v2 support to be removed in Chrome in 2023
I noticed a warning in the developer setting of the extension page.

See https://developer.chrome.com/blog/mv2-transition/ and https://developer.chrome.com/docs/extensions/migrating/mv2-sunset/ for details.

Is there an interest to port it to v3? (I can help if the project is still meant to be maintained).

### PR DESCRIPTION
**Pull request by Ryuno-Ki**
I've good news and bad news for you.

The good news: I was able to port the code to the Manifest Version 3 (breaking change. I've bumped the version).

Bad news: It doesn't work like this in Firefox. [Bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1860304)

You would need to swap out `background.service_worker` for `background.scripts` (and put the JS path in an Array) to submit it to Firefox.

As a cherry on top I've implemented an options page :cat:

### CODE REVIEW

**Comment by kootenpv** [comment]
Amazing my dude! I am still using it every day so I would have been lost without you on this breaking change 😬

Will this V3 already work? If so, I'll give it a try.

Also, I noticed I'm storing duplicate data: I guess event on page load triggers twice somehow, not sure if you  experience the same?

**Comment by Ryuno-Ki** [comment]
Hey there,

I keep my promises :cat: 

Yes, it is working for me. Notice that Firefox needs a slightly different manifest.

I can imagine, that you are recording once for when the index.html finishes loading and another time for SPA changes (History API updates).

**Comment by kootenpv** [comment]
Awesome! I tested all the functionality and everything works, so nice!!

**Comment by kootenpv** [comment]
I'm curious which data you track? videoswatched as well? or mostly just interested in the web visits?

**Comment by Ryuno-Ki** [comment]
Given the tracking, I'm watching videos using [Invidious](https://docs.invidious.io/instances/#list-of-public-invidious-instances-sorted-from-oldest-to-newest) myself.

So, yes, only visited websites.

**Pull request merged**
